#pragma once

namespace sm70::decode::sparse_fp8 {

#ifndef FLASH_MLA_SM70_SPARSE_DECODE_CTA_THREADS
#define FLASH_MLA_SM70_SPARSE_DECODE_CTA_THREADS 256
#endif

#ifndef FLASH_MLA_SM70_SPARSE_DECODE_K_TILE
#define FLASH_MLA_SM70_SPARSE_DECODE_K_TILE 32
#endif

#ifndef FLASH_MLA_SM70_SPARSE_DECODE_USE_MMA_884_QK
#define FLASH_MLA_SM70_SPARSE_DECODE_USE_MMA_884_QK 0
#endif

#ifndef FLASH_MLA_SM70_SPARSE_DECODE_USE_MMA_884_PV
#define FLASH_MLA_SM70_SPARSE_DECODE_USE_MMA_884_PV 0
#endif

#ifndef FLASH_MLA_SM70_SPARSE_DECODE_USE_MMA_884_ONLINE
#define FLASH_MLA_SM70_SPARSE_DECODE_USE_MMA_884_ONLINE 1
#endif

static constexpr int HEAD_DIM_QK_V32 = 576;
static constexpr int HEAD_DIM_QK_MODEL1 = 512;
static constexpr int HEAD_DIM_V = 512;
static constexpr int V32_NOPE_DIM = 512;
static constexpr int V32_ROPE_DIM = 64;
static constexpr int V32_NUM_SCALES = 4;
static constexpr int V32_SCALE_GROUP = 128;
static constexpr int V32_BYTES_PER_TOKEN = 656;
static constexpr int MODEL1_NOPE_DIM = 448;
static constexpr int MODEL1_ROPE_DIM = 64;
static constexpr int MODEL1_NUM_SCALES = 7;
static constexpr int MODEL1_SCALE_GROUP = 64;
static constexpr int MODEL1_BYTES_PER_TOKEN = 584;
static constexpr int MODEL1_TOKEN_DATA_BYTES = 576;
static constexpr int MODEL1_SCALE_STRIDE = 8;
static constexpr int NUM_THREADS = FLASH_MLA_SM70_SPARSE_DECODE_CTA_THREADS;
static constexpr int MAX_TOPK_ALPHA = 8192;
static constexpr int TOPK_BLOCK_SIZE = 64;
static constexpr int SPARSE_K_TILE = FLASH_MLA_SM70_SPARSE_DECODE_K_TILE;
static constexpr bool USE_MMA_884_QK = FLASH_MLA_SM70_SPARSE_DECODE_USE_MMA_884_QK != 0;
static constexpr bool USE_MMA_884_PV = FLASH_MLA_SM70_SPARSE_DECODE_USE_MMA_884_PV != 0;
static constexpr bool USE_MMA_884_ONLINE = FLASH_MLA_SM70_SPARSE_DECODE_USE_MMA_884_ONLINE != 0;
static constexpr int MMA_884_REGISTER_OUTPUT_CTA_THREADS = 256;
static constexpr int MMA_884_ONLINE_LONG_K_TILE = 16;
static constexpr int MMA_884_ONLINE_LONG_K_TILE_THRESHOLD = 512;
static constexpr int MMA_884_ONLINE_SCALAR_COUNT = 5;
static constexpr int MMA_884_BATCH2_VERIFY_SCALAR_COUNT = 8;
static constexpr int MMA_884_ONLINE_REDUCE_SCRATCH = NUM_THREADS / 32;
static constexpr int MAX_DV_PER_THREAD = (HEAD_DIM_V + NUM_THREADS - 1) / NUM_THREADS;

#ifndef FLASH_MLA_SM70_SPARSE_DECODE_DOUBLE_BUFFER
#define FLASH_MLA_SM70_SPARSE_DECODE_DOUBLE_BUFFER 0
#endif

#ifndef FLASH_MLA_SM70_SPARSE_DECODE_STAGE_Q_HALF
#define FLASH_MLA_SM70_SPARSE_DECODE_STAGE_Q_HALF 1
#endif

#ifndef FLASH_MLA_SM70_SPARSE_DECODE_KV_ROW_PAD_HALF
#define FLASH_MLA_SM70_SPARSE_DECODE_KV_ROW_PAD_HALF 4
#endif

#ifndef FLASH_MLA_SM70_SPARSE_DECODE_S0C3_ABLATION
#define FLASH_MLA_SM70_SPARSE_DECODE_S0C3_ABLATION 0
#endif

#ifndef FLASH_MLA_SM70_SPARSE_DECODE_FAST_E4M3
#define FLASH_MLA_SM70_SPARSE_DECODE_FAST_E4M3 1
#endif

#ifndef FLASH_MLA_SM70_SPARSE_DECODE_FAST_BF16_ROUND
#define FLASH_MLA_SM70_SPARSE_DECODE_FAST_BF16_ROUND 1
#endif

#ifndef FLASH_MLA_SM70_SPARSE_DECODE_PV_P_CACHE
#define FLASH_MLA_SM70_SPARSE_DECODE_PV_P_CACHE 1
#endif

#ifndef FLASH_MLA_SM70_SPARSE_DECODE_V_FRAGMENT_VECTOR
#define FLASH_MLA_SM70_SPARSE_DECODE_V_FRAGMENT_VECTOR 0
#endif

#ifndef FLASH_MLA_SM70_SPARSE_DECODE_BATCH2_VERIFY
#define FLASH_MLA_SM70_SPARSE_DECODE_BATCH2_VERIFY 1
#endif

static constexpr bool USE_DOUBLE_BUFFER = FLASH_MLA_SM70_SPARSE_DECODE_DOUBLE_BUFFER != 0;
static constexpr bool USE_STAGE_Q_HALF = FLASH_MLA_SM70_SPARSE_DECODE_STAGE_Q_HALF != 0;
static constexpr int KV_ROW_PAD_HALF = FLASH_MLA_SM70_SPARSE_DECODE_KV_ROW_PAD_HALF;
static constexpr int S0C3_ABLATION = FLASH_MLA_SM70_SPARSE_DECODE_S0C3_ABLATION;
static constexpr bool USE_FAST_E4M3 = FLASH_MLA_SM70_SPARSE_DECODE_FAST_E4M3 != 0;
static constexpr bool USE_FAST_BF16_ROUND = FLASH_MLA_SM70_SPARSE_DECODE_FAST_BF16_ROUND != 0;
static constexpr bool USE_PV_P_CACHE = FLASH_MLA_SM70_SPARSE_DECODE_PV_P_CACHE != 0;
static constexpr bool USE_V_FRAGMENT_VECTOR =
    FLASH_MLA_SM70_SPARSE_DECODE_V_FRAGMENT_VECTOR != 0;
static constexpr bool USE_BATCH2_VERIFY = FLASH_MLA_SM70_SPARSE_DECODE_BATCH2_VERIFY != 0;

static_assert(KV_ROW_PAD_HALF == 0 || KV_ROW_PAD_HALF == 4 || KV_ROW_PAD_HALF == 8,
              "FLASH_MLA_SM70_SPARSE_DECODE_KV_ROW_PAD_HALF must be 0, 4, or 8");
static_assert(S0C3_ABLATION >= 0 && S0C3_ABLATION <= 4,
              "FLASH_MLA_SM70_SPARSE_DECODE_S0C3_ABLATION must be in [0, 4]");
static_assert(FLASH_MLA_SM70_SPARSE_DECODE_FAST_E4M3 == 0 ||
              FLASH_MLA_SM70_SPARSE_DECODE_FAST_E4M3 == 1,
              "FLASH_MLA_SM70_SPARSE_DECODE_FAST_E4M3 must be 0 or 1");
static_assert(FLASH_MLA_SM70_SPARSE_DECODE_FAST_BF16_ROUND == 0 ||
              FLASH_MLA_SM70_SPARSE_DECODE_FAST_BF16_ROUND == 1,
              "FLASH_MLA_SM70_SPARSE_DECODE_FAST_BF16_ROUND must be 0 or 1");
static_assert(FLASH_MLA_SM70_SPARSE_DECODE_PV_P_CACHE == 0 ||
              FLASH_MLA_SM70_SPARSE_DECODE_PV_P_CACHE == 1,
              "FLASH_MLA_SM70_SPARSE_DECODE_PV_P_CACHE must be 0 or 1");
static_assert(FLASH_MLA_SM70_SPARSE_DECODE_BATCH2_VERIFY == 0 ||
              FLASH_MLA_SM70_SPARSE_DECODE_BATCH2_VERIFY == 1,
              "FLASH_MLA_SM70_SPARSE_DECODE_BATCH2_VERIFY must be 0 or 1");

__host__ __device__ __forceinline__ constexpr int kv_row_stride(int head_dim) {
    return head_dim + KV_ROW_PAD_HALF;
}

}  // namespace sm70::decode::sparse_fp8
